project:
  analyst-name: Your Name
  project-name: 'Test'
  project-decription: "ToDo"
  organism: mouse
  run_cell_cycle: 'TRUE'
  samples: -"Sample1" -"Sample2" -"Sample3" -"Sample4"
data:
  import-h5: no
  parent_directory_path: path/to/CellRanger
  rds-file-path: path/to/results
analysis:
  run_tests: no
  node_type: analytics
  part1:
    part1_rds_save_filename: _0_raw_seurat_object.RDS
    part1_report_tables_filename: part1_tables_for_report.RData
    part1_suffix: ''
    generate_metrics_tables: 'TRUE'
    run_SoupX: 'FALSE'
    ggplot_dir: ggplot
  part2:
    mito_ceiling: 5
    RNA_count_floor: 500
    RNA_count_ceiling: 25000
    feature_count_floor: 300
    feature_count_ceiling: 6000
    rbc_ceiling: 100
    ribo_floor: 5
    part2_rds_open_filename: _0_raw_seurat_object.RDS
    merged_seurat_obj_file: _2_seurat5_obj_merged.RDS
    integrated_seurat_obj_file: _3_seurat5_obj_integrated.RDS
    clustered_seurat_obj_file: _4_seurat5_obj_clustered.RDS
    part2_report_tables_filename: part2_tables_for_report.RData
    marker_gene_dir: marker_genes
    run_doubletFinder: 'FALSE'
    part2_suffix: ''
    clustering_resolution: None
    num_clusters: 0
